[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm install --production --legacy-peer-deps"]

[start]
cmd = "node server/index.js"

[variables]
NODE_ENV = "production"